language: node_js

node_js:
  - 12

env:
  global:
    - YARN_VERSION="--version 1.19.1"

before_install:
  # Install Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- $YARN_VERSION
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install --frozen-lockfile

script:
  - yarn test
